### ISSUE TITLE
[ERROR] user#signchangeemail (I18n::MissingInterpolationArgument) "missing interpolation argument…"

### ISSUE THREAD

**Issue by garethrees** [mysociety/bilmehakki-theme#29]
```
An I18n::MissingInterpolationArgument occurred in user#signchangeemail:

missing interpolation argument "info_request_title" in {:site_name=>"4982*"} (" {{info_request_title}} sitesindeki yeni email adresinizi doğrulayın" given)
lib/i18n_fixes.rb:35:in `block in gettext_interpolate'

-------------------------------
Request:
-------------------------------

* URL : https://bilmehakki.org/profile/change_email
* Parameters: {"utf8"=>"✓", "authenticity_token"=>"REDACTED", "signchangeemail"=>{"old_email"=>"REDACTED@hotmail.com", "new_email"=>"REDACTED@hotmail.com"}, "submitted_signchangeemail_do"=>"1", "commit"=>" 4982* sitesindeki email adresini değiştir", "controller"=>"user", "action"=>"signchangeemail"}
* Rails root: /data/vhost/turkey.alaveteli.org/alaveteli-2020-10-01T16-35-29
* Timestamp : 2020-10-05 22:35:16 +0300

-------------------------------
Session:
-------------------------------

* session id: [FILTERED]
* data: {"session_id"=>"REDACTED",
"locale"=>"tr",
"_csrf_token"=>"REDACTED",
"remember_me"=>false,
"user_id"=>328,
"ttl"=>2020-10-05 20:34:53 +0100,
"post_redirect_token"=>"ch6srv8u3om7v1f17k4"}

-------------------------------
Backtrace:
-------------------------------

lib/i18n_fixes.rb:35:in `block in gettext_interpolate'
lib/i18n_fixes.rb:31:in `gsub'
lib/i18n_fixes.rb:31:in `gettext_interpolate'
lib/i18n_fixes.rb:11:in `_'
app/mailers/user_mailer.rb:33:in `changeemail_confirm'
actionpack (3.2.22.2) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.22.2) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:45:in `process'
actionmailer (3.2.22.2) lib/action_mailer/base.rb:459:in `process'
actionmailer (3.2.22.2) lib/action_mailer/base.rb:453:in `initialize'
actionmailer (3.2.22.2) lib/action_mailer/base.rb:439:in `new'
actionmailer (3.2.22.2) lib/action_mailer/base.rb:439:in `method_missing'
app/controllers/user_controller.rb:263:in `signchangeemail'
actionpack (3.2.22.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.22.2) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:602:in `block in _run__2836315086467283947__process_action__1741377933028834203__callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_1323'
app/controllers/application_controller.rb:105:in `record_memory'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_1323'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:601:in `_run__2836315086467283947__process_action__1741377933028834203__callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.22.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.22.2) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.22.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.22.2) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.22.2) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.22.2) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.22.2) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.22.2) lib/action_dispatch/routing/route_set.rb:608:in `call'
exception_notification (3.0.1) lib/exception_notifier.rb:41:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.7) lib/rack/etag.rb:23:in `call'
rack (1.4.7) lib/rack/conditionalget.rb:35:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/cookies.rb:341:in `call'
lib/strip_empty_sessions.rb:13:in `call'
activerecord (3.2.22.2) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.22.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `_run__4038653102854823706__call__3075432520078395986__callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.22.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.22.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.22.2) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.22.2) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.22.2) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.7) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.22.2) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.7) lib/rack/lock.rb:15:in `call'
actionpack (3.2.22.2) lib/action_dispatch/middleware/static.rb:83:in `call'
rack-utf8_sanitizer (1.3.0) lib/rack/utf8_sanitizer.rb:15:in `call'
railties (3.2.22.2) lib/rails/engine.rb:484:in `call'
railties (3.2.22.2) lib/rails/application.rb:231:in `call'
railties (3.2.22.2) lib/rails/railtie/configurable.rb:30:in `method_missing'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by gbp** [comment]
Translation fixed at: https://www.transifex.com/mysociety/alaveteli/translate/#tr/apppot/2984955
